class Locator():

    # Login page objects
    username_textbox_name = "ion-input-0"
    password_textbox_name = "ion-input-1"
    login_button_tag_name = "ion-button"
    interface_button = "//section/ion-button"
    planing_bar = "//ion-tab-button[3]/ion-icon"

    # home page objects
    into_detail_page = "//ion-tab-button[2]/ion-icon"
    into_detail_crops = "//div/ion-list/ion-item[3]/ion-label/h3"
    add_crops = "//app-product/ion-content/section/ion-button"
    add_garden = "//section/section/ion-button"
    into_detail_garden = "//div/ion-list/ion-item[2]/ion-label/h3"
    garden_form = "//ion-segment-button[2]"

    # edit page objects
    upload_image_object = "imageUpload1"
    edit_address_name = "ion-input-1"
    edit_first_name_name = "ion-input-2"
    edit_email_name = "ion-input-3"
    edit_phone_number_name = "ion-input-4"
    next_confirm = "//ion-col[2]/ion-button"
    go_main_menu = "//ion-icon[@name='menu-outline']"
    edit_garden_detail = "//ion-item[2]/ion-label/h3"
    edit_seed_detail = ""

    # Add Interface
    click_factor = "//app-activity-list/ion-content/section/ion-list/ion-item/ion-label/h3"
    click_plant = "//ion-item[3]/ion-label/h3"
    click_prepare = "//ion-item[2]/ion-label/h3"
    click_caring = "//app-activity-list/ion-content/section/ion-list/ion-item[4]/ion-label/h3"
    click_predict = "//app-activity-list/ion-content/section/ion-list/ion-item[5]/ion-label/h3"
    click_harvest = "//app-activity-list/ion-content/section/ion-list/ion-item[6]/ion-label/h3"
    click_selling = "//app-activity-list/ion-content/section/ion-list/ion-item[7]/ion-label/h3"

    # Data Planning
    planing_per_year = "//ion-button[2]"
    planning_button = "//ion-button"
    planning_garden = "//ion-select"
    planning_garden_select = "//button/div/div[2]"
    planning_confirm = "//button[2]/span"
    planning_crops = "//ion-item[2]/ion-select"
    planning_crops_select = "//button[3]/div/div[2]"
    planning_area = "//ion-input/input"
    planning_area_dd = "//div/ion-item/ion-select"
    planning_area_select = "//button[3]/div/div[2]"
    planning_amount = "//ion-item[3]/ion-input/input"
    planning_amount_dd = "//ion-item[3]/ion-select"
    planning_amount_select = "//button[4]/div/div[2]"
    planning_value = "//ion-item[4]/ion-input/input"
    planning_value_dd = "//ion-item[4]/ion-select"
    planning_value_select = "//button[4]/div/div[2]"
    planning_submit = "//form/ion-button"
    planning_saved = "//ion-col[2]/ion-button"


    # Data Garden
    detail_garden = "//ion-segment-button[@value='garden']"
    tab_detail_garden = "//ion-button"
    upload_garden_image = "imageUpload1"
    name_garden = "//ion-input/input"
    number_garden = "//ion-item[2]/ion-input/input"
    area_garden = "//div/ion-item/ion-input/input"
    garden_selection_unit = "//button[3]/div/div[2]"
    garden_input_unit = "//ion-select"
    garden_input_accept = "//button[2]/span"
    garden_owner = "//div/app-modal-garden/ion-content/section[2]/form/ion-list/ion-item[3]/ion-select"
    garden_owner_selection = "//button/div/div[2]"
    garden_in_district = "//div/app-modal-garden/ion-content/section[2]/form/ion-list/ion-item[7]/ion-select"
    garden_status = "//div/app-modal-garden/ion-content/section[2]/form/ion-list/ion-item[9]/ion-select"
    garden_status_selection = "//button[4]/div/div[2]"
    garden_submit_form = "//form/ion-button"
    garden_submit_confirm = "//button[2]/span"

    # Data Crops
    detail_crops = "//ion-item[3]/ion-label/h3"
    crops_select = "//ion-button"
    crops_category = "//div/app-modal-product/ion-content/section/form/ion-list/ion-item/ion-select"
    crops_select_category = "//button[3]/div/div[2]"
    crops_accept = "//button[2]/span"
    crops_planting = "//div/app-modal-product/ion-content/section/form/ion-list/ion-item[2]/ionic-selectable/div/button"
    crops_select_planting = "//ion-item-group/ion-item[2]/ion-label"
    crops_standard = "//div/app-modal-product/ion-content/section/form/ion-list/ion-item[3]/ion-select"
    crops_select_standard = "//button[5]/div/div[2]"
    crops_submit = ".ion-activated"
    crops_submit_confirm = "//button[2]/span"
    crop_submit_version = "//ion-list/ion-button"

    quiet_peace = ""

    # Factor Page
    edit_profile_factor = ".ion-activated"
    confirm_profile_factor = "imageUpload1"
    factor_next_confirm = "//ion-col[2]/ion-button"
    choose_category_factor = "//ion-select"
    add_factor_name = "//ion-input/input"
    add_factor_value = "//ion-item[4]/ion-input/input"
    add_factor_price = "//ion-item[5]/ion-input/input"
    add_factor_category = "//ion-select"
    add_factor_category_selection = "//button/div/div[2]"
    add_factor_category_confirm = "//button[2]/span"
    add_factor_unit = "//ion-item[4]/ion-select"
    add_factor_unit_selection = "//button[5]/div/div[2]"
    add_factor_unit_confirm = "//button[2]/span"
    add_factor_submit = "//form/ion-button"
    add_factor_confirm_submit = "//button[2]/span"

    # Prepare Page
    prepare_card = "//ion-card-subtitle"
    prepare_next = "//ion-col[2]/ion-button"
    prepare_selected = "//img"
    prepare_selected2 = "//ion-col[13]/ion-card/img"
    prepare_selected3 = "//ion-col[6]/ion-card/img"
    prepare_segment = "//ion-segment-button[4]"
    prepare_menu = "//input"
    prepare_price = "//ion-item[2]/ion-input/input"
    prepare_confirm = "//button[2]/span"


    # Plant Page

    confirm_profile_planting = "imageUpload1"
    plant_next_confirm = "//button[2]/span"
    plant_select_image = "//img"
    plant_next = "//ion-col[2]/ion-button"
    plant_segment = "//ion-segment-button[4]"
    plant_selected = "//img"
    plant_menu = "//input"
    plant_price = "//ion-item[2]/ion-input/input"
    plant_category = "//ion-item[2]/ion-select"
    plant_category_selected = "//button/div/div[2]"
    plant_seed = "//ion-item[3]/ion-select"
    plant_seed_selected = "//button[3]/div/div[2]"
    plant_submit = "//ion-col[2]/ion-button"

    # Care Page
    upload_care_image = "imageUpload1"
    caring_select = "//ion-card[3]/ion-grid/ion-row/ion-col[2]/ion-item"
    next_tab_function = "//ion-col[2]/ion-button"
    care_choose_plant = "//span"
    care_choose_plant2 = "//ion-col[5]/ion-card/img"
    care_choose_plant3 = "//ion-col[8]/ion-card/img"
    care_problem = "//ion-card-title"
    care_confirm_select = "//ion-buttons[2]/ion-button"
    care_paid = "//input"
    care_submit = "//ion-col[2]/ion-button"
    care_submit_confirm = "//button[2]/span"

    # Predict Page
    upload_predict_image = "imageUpload1"
    predict_next = "//ion-col[2]/ion-button"
    predict_planting = "//ion-card[2]/ion-grid/ion-row/ion-col[2]/ion-card-content"
    predict_selection = "//ion-content/ion-card/ion-grid/ion-row/ion-col[2]/ion-card-content/p"
    predict_confirm = "//ion-buttons[2]/ion-button"
    predict_marget = "//ion-grid[2]/ion-row/ion-col/ion-card/img"
    predict_marget_select = "//button/div/div"
    predict_accept = "//button[2]/span"
    predict_value = "//ion-input/input"
    predict_unit = "//ion-select"
    predict_unit_selection = "//button[4]/div/div[2]"
    predict_submit = "//ion-col[2]/ion-button"
    predict_submit_confirm = "//button[2]/span"

    # Harvest Page
    upload_harvest_image = "imageUpload1"
    harvest_next = "//ion-col[2]/ion-button"
    harvest_device = "//img"
    harvest_crops = "//ion-button"
    harvest_selection = "//div/app-modal-checkbox-product/ion-content/ion-card/ion-grid/ion-row/ion-col/span"
    harvest_accept = "//ion-buttons[2]/ion-button"
    harvest_value = "//input"
    harvest_unit = "//ion-select"
    harvest_delete = "//ion-item[2]/ion-input/input"
    harvest_keep = "//ion-item[3]/ion-input/input"
    harvest_unit_selection = "//button[2]/div/div[2]"
    harvest_select_accept = "//button[2]/span"
    harvest_paid = "//ion-list[3]/ion-item/ion-input/input"
    harvest_submit = "//ion-col[2]/ion-button"

    # Selling Page
    selling_crops = "//ion-button"
    selling_selection = "//img"
    selling_crops_select = "//p[2]"
    selling_crops_confirm = "//ion-buttons[2]/ion-button"
    selling_marget = "//ion-grid[2]/ion-row/ion-col/ion-card/span"
    selling_marget_select = "//button/div/div"
    selling_confirm = "//button[2]/span"
    selling_value = "//ion-input/input"
    selling_unit = "//ion-item[3]/ion-select"
    selling_unit_select = "//button[4]/div/div[2]"
    selling_paid = "//ion-item[4]/ion-input/input"
    selling_price = "//ion-item[5]/ion-input/input"
    selling_submit = "//ion-col[2]/ion-button"
    selling_submit_confirm = "//button[2]/span"

    # scroll bar
    scroll_bar = "inner-scroll scroll-y"

    # Profile Page
    profile_page = "//h3"
    profile_upload_image = "//ion-button"
    profile_name = "//ion-input/input"
    profile_email = "//ion-item[2]/ion-input/input"
    profile_birthday = "//app-date-time/ion-button"
    profile_birthday_day = "//ion-col/ion-item/ion-select"
    profile_birthday_days = "//button[4]/div/div"
    profile_birthday_month = "//ion-col[2]/ion-item/ion-select"
    profile_birthday_months = "//button[5]/div/div[2]"
    profile_birthday_year = "//ion-col[3]/ion-item/ion-select"
    profile_birthday_years = "//button[99]/div/div[2]"
    profile_birthday_ok = "//button[2]/span"
    profile_birthday_accept = "//ion-buttons[2]/ion-button"
    profile_phone = "//ion-item[4]/ion-input/input"
    profile_dialog = ""
    profile_address = "//textarea"
    profile_submit = "//form/ion-button"
    profile_confirm = "//button[2]/span"

